### ISSUE TITLE
A small correction to 'Deploying to a single organization Hyperledger Fabric' Page

### ISSUE THREAD

**Issue by R1j1t** [hyperledger/hyperledger.github.io#3]
In Step Eight, the command mentioned is `composer network start -c PeerAdmin@fabric-network -a tutorial-network.bna -A admin -S adminpw` but the `.bna` file created in the Developer Tutorial is `tutorial-network@0.0.1.bna` So I propose that the modified command on the page 'Deploying to a single organization Hyperledger Fabric' be `composer network start -c PeerAdmin@fabric-network -a tutorial-network\@0.0.1.bna -A admin -S adminpw`

I leave the rest to the developers to decide. Just a small suggestion from my end

**Comment by tkuhrt** [comment]
Was this opened against the correct repo @R1j1t?

**Comment by R1j1t** [comment]
I will also migrate this issue to github.com/hyperledger/composer
