### ISSUE TITLE
Correction in 'Developer Tutorial' page

### ISSUE THREAD

**Issue by R1j1t** [hyperledger/hyperledger.github.io#4]
I was going through the tutorial and I found a place where the documentation was not precise. Under **Adding JavaScript transaction logic** the `logic.js` files are present in two different directories. First in `lib` and other in `test`. I would seriously encourage you to mention it explicitly to make changes to `logic.js` under `lib` repo.

**Comment by tkuhrt** [comment]
Was this opened against the correct repo @R1j1t

**Comment by R1j1t** [comment]
The problem I encountered was on the documentation page and so I believe it is opened against the correct repo @tkuhrt

**Comment by tkuhrt** [comment]
@R1j1t : Was this found under Hyperledger.github.io/Composer/? If so, this would be for GitHub.com/Hyperledger/Composer. This repo only generates https://hyperledger.github.io, but nothing under that.

**Comment by R1j1t** [comment]
Yes it was found Hyperledger.github.io/Composer. Should I add this issue there?

**Comment by tkuhrt** [comment]
Yes, please.
